Create Technical-writer.md
mayadata-io/culture pull request #114
Opened 2020-11-03 04:47 UTC by Shreyangi

2020-11-26 12:12 UTC, bobek reviewed
Can we please update the language to make it a more welcoming to people? Thx

2020-11-26 12:12 UTC, bobek commented on job-roles/Technical-writer.md
> +### Requirements:
```suggestion
## Requirements:
```

2020-11-26 12:12 UTC, bobek commented on job-roles/Technical-writer.md
> +### Responsibilities:
```suggestion
## Responsibilities:
```

2020-12-15 04:03 UTC, Shreyangi commented
@kmova Can you please review this ?

2020-12-15 06:59 UTC, bobek requested changes

2020-12-15 06:59 UTC, bobek commented on job-roles/Technical-writer.md
> +* MUST have internet access, and be comfortable working at a remote-first company
Please, change language to be closer to other job descriptions. We don't write RFC here and would not like to scare off potential candidates.

2020-12-15 06:59 UTC, bobek commented on job-roles/Technical-writer.md
> +# Tecnical Writer
```suggestion
# Technical Writer
```
Please run the doc through spell checker.

2020-12-21 03:48 UTC, Shreyangi commented
@bobek @kmova Can you please review the changes?

2020-12-21 10:20 UTC, bobek approved these changes

2020-12-21 10:20 UTC, merged