Fix openness link in remote-first
mayadata-io/culture pull request #120
Opened 2020-12-01 18:08 UTC by arne-rusek

2020-12-02 00:36 UTC, kellyhair requested changes
Thank you Arne!

There's some extra spaces that need updating - "ifferent  time" to "ifferent time"

This is a great addition. It's about results & not hours worked!

2020-12-02 09:32 UTC, arne-rusek commented
@kellyhair please take another look. While at it I fixed extra spaces everywhere (including between sentences - it seems that today's agreement is one - and we used both). I have another MR in pipeline that will use markdown linter to automatically fix this for later additions.

2020-12-13 20:51 UTC, bobek approved these changes

2020-12-14 14:17 UTC, kellyhair approved these changes
Looks like the whitespace was fixed. Thanks @arne-rusek .

2020-12-15 11:31 UTC, merged